#!/usr/bin/ruby
#
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

# Check sources to see how long it has been since the last upload.

include ActionView::Helpers::DateHelper

data = ActiveRecord::Base.connection.execute "
  SELECT label source, MAX(created_at) latest FROM items
  JOIN item_paths ON items.id = item_paths.item_id
  JOIN sources ON source_id = sources.id
  GROUP BY 1
  ORDER BY 2 DESC
  "

data.each do |row|
  puts "#{sprintf "%-15s", row.first} #{time_ago_in_words row.last} ago"
end
