#!/usr/bin/env ruby
# Convert from cheese database schema to hypercheese

require 'mysql2'

@old = Mysql2::Client.new( :host => "localhost", :username => "cheese", :password => "cheesy", :database => "cheese" )
@new = Mysql2::Client.new( :host => "localhost", :username => "cheese", :password => "cheesy", :database => "hypercheese" )

unless File.respond_to? :binwrite
  class File
    def self.binwrite path, content
      File.open path, 'wb' do |f|
        f.write content
      end
    end
  end
end

$stdout.sync = true

def table old, new=nil
  new ||= old
  # old_schema = @old.query("SHOW CREATE TABLE `#{old}`").first["Create Table"]
  # new_schema = @new.query("SHOW CREATE TABLE `#{new}`").first["Create Table"]
  # File.binwrite "/tmp/oldschema", old_schema + "\n"
  # File.binwrite "/tmp/newschema", new_schema + "\n"
  # system( "diff -u /tmp/oldschema /tmp/newschema" )
  @new.query "BEGIN WORK"
  @new.query "DELETE FROM `#{new}`"
  results = @old.query "SELECT * FROM `#{old}`"
  puts "#{old} -> #{new} (#{results.count})" if $stdout.tty?
  results.each( :symbolize_keys => true ) do |row|
    print "#{row[:id]}\r" if $stdout.tty?
    res = yield row if block_given?
    next if res == false
    keys = row.keys.join  ", "
    values = row.values.map do |_|
      if _.nil?
        "NULL"
      else
        "'" + @new.escape(_.to_s) + "'"
      end
    end.join ", "
    @new.query( "INSERT INTO `#{new}` (#{keys}) VALUES (#{values})" )
  end
  @new.query "COMMIT"
end

table :accounts, :users do |row|
  row[:encrypted_password] = row.delete :password_hash
  row[:encrypted_password] ||= SecureRandom.hex 20
  row[:role] = 'user'

  if row[:email] && row[:email].empty?
    row.delete :email
  end

  if row[:email] && row[:email] !~ /@/
    row[:username] = row.delete :email
    row[:email] = "#{row[:username]}@null"
  end

  if !row[:email] && row[:uid]
    row[:username] = row[:uid]
    row[:email] = "#{row[:uid]}@facebook.null"
  end

  puts "#{row[:email].inspect}"

  %w{first_name last_name image gender}.each do |field|
    row.delete field.to_sym
  end
end

table :tags do |row|
  row[:parent_tag_id] = row.delete :parent_id
  row[:icon_item_id] = row.delete :icon_id
  row.delete :account_id
end

table :item_tags

table :events
table :items do |row|
  row.delete :deleted
  row.delete :location_id
  row.delete :length
  row[:variety] = row.delete :type
  row[:created_at] = row[:updated_at] = row.delete(:added)
end

table :item_paths
